name: word_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  flutter_tts: ^4.2.0
  english_words: ^4.0.0
  speech_to_text: ^7.0.0
  pdf: ^3.11.1
  share_plus: ^12.0.0
  confetti: ^0.8.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1
  string_similarity: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Icon2.png
    - assets/Icon_HomePage.png

  
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/Icon2.png"
  min_sdk_android: 21 

flutter_native_splash:
  color: "#ffffff" 
  image: assets/Icon2.png
  image_dark: assets/Icon2.png
  android_12:
    image: assets/Icon2.png
    image_dark: assets/Icon2.png
  ios: true
  android: true
  fullscreen: true


# flutter pub run flutter_native_splash:create
# flutter pub run flutter_launcher_icons