name: word_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.3.6
  flutter_tts: ^4.2.0
  english_words: ^4.0.0
  speech_to_text: ^6.1.1
  pdf: ^3.11.1
  share_plus: ^10.1.4
  confetti: ^0.8.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Icon.png


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/Icon.png"
  min_sdk_android: 21 # Optional, for Android

flutter_native_splash:
  color: "#A6A6A6"  # Light gray from the icon
  image: assets/Icon.png
  color_dark: "#A6A6A6"  # Same color for dark mode consistency
  image_dark: assets/Icon.png
  android_12:
    color: "#A6A6A6"
    image: assets/Icon.png
    color_dark: "#A6A6A6"
    image_dark: assets/Icon.png
  ios: true
  android: true
  fullscreen: true