class EnglishSentences {
  static const List<String> kumon7aSentences = [
    "I see a dog.",
    "You have a cat.",
    "We go to school.",
    "They play with toys.",
    "He runs to me.",
    "She eats an apple.",
    "It is a bat.",
    "I like my car.",
    "You see the sun.",
    "We have a ball.",
    "They make a cake.",
    "He reads a book.",
    "She sings a song.",
    "It jumps up high.",
    "I draw a star.",
    "You catch the bus.",
    "We sit on grass.",
    "They ride a bike.",
    "He picks a pen.",
    "She opens the box.",
    "It rings the bell.",
    "I wash my hands.",
    "You kick the ball.",
    "We clap our hands.",
    "They run to class.",
    "He cuts the cake.",
    "She bakes a pie.",
    "It rolls on road.",
    "I drink my milk.",
    "You write a name.",
    "We stand in line.",
    "They hold a cup.",
    "He finds a hat.",
    "She throws the toy.",
    "It shines at night.",
    "I close the door.",
    "You jump on bed.",
    "We draw a fish.",
    "They hug a doll.",
    "He climbs a tree.",
    "I paint a house.",
    "You feed the fish.",
    "We walk to park.",
    "They kick a ball.",
    "She cleans the desk.",
    "I touch the sky.",
    "You pull a rope.",
    "We lift a box.",
    "They wave a flag.",
    "He drops a coin.",
    "She ties a knot.",
    "It flies in air.",
    "I fold a paper.",
    "You push a cart.",
    "We plant a seed.",
    "They build a fort.",
    "He swings a bat.",
    "She sweeps the floor.",
    "It hops on ground.",
    "I carry a bag.",
    "You call a friend.",
    "We watch a bird.",
    "They fix a toy.",
    "He throws a stick.",
    "She paints a fence.",
    "It swims in water.",
    "I open a book.",
    "You climb a hill.",
    "We chase a kite.",
    "They hold a rope.",
    "He kicks a stone.",
    "She draws a cloud.",
    "It runs in field.",
    "I wave my hand.",
    "You read a sign."
  ];

  static const List<String> kumon6aSentences = [
    "I see a big dog.",
    "You have a small cat.",
    "We go to a new school.",
    "They play with funny toys.",
    "He runs very fast.",
    "She eats a red apple.",
    "It is a big bat.",
    "I like my blue car.",
    "You see the bright sun.",
    "We have a round ball.",
    "They make a sweet cake.",
    "He reads a short book.",
    "She sings a happy song.",
    "It jumps up high.",
    "I draw a yellow star.",
    "You catch the big bus.",
    "We sit on soft grass.",
    "They ride a black bike.",
    "He picks a long pen.",
    "She opens the small box.",
    "It rings the loud bell.",
    "I wash my dirty hands.",
    "You kick the red ball.",
    "We clap our little hands.",
    "They run to the big class.",
    "He cuts the tasty cake.",
    "She bakes a hot pie.",
    "It rolls on a wet road.",
    "I drink my cold milk.",
    "You write a short name.",
    "We stand in a long line.",
    "They hold a full cup.",
    "He finds a yellow hat.",
    "She throws the soft toy.",
    "It shines at dark night.",
    "I close the heavy door.",
    "You jump on the soft bed.",
    "We draw a big fish.",
    "They hug a cute doll.",
    "He climbs a tall tree.",
    "I paint a green house.",
    "You feed the tiny fish.",
    "We walk to a small park.",
    "They kick a blue ball.",
    "She cleans the dusty desk.",
    "I touch the wide sky.",
    "You pull a strong rope.",
    "We lift a heavy box.",
    "They wave a bright flag.",
    "He drops a shiny coin.",
    "She ties a tight knot.",
    "It flies in clear air.",
    "I fold a thin paper.",
    "You push a big cart.",
    "We plant a green seed.",
    "They build a tall fort.",
    "He swings a heavy bat.",
    "She sweeps the clean floor.",
    "It hops on dry ground.",
    "I carry a full bag.",
    "You call a close friend.",
    "We watch a tiny bird.",
    "They fix a broken toy.",
    "He throws a long stick.",
    "She paints a white fence.",
    "It swims in clear water.",
    "I open a thick book.",
    "You climb a steep hill.",
    "We chase a high kite.",
    "They hold a strong rope.",
    "He kicks a small stone.",
    "She draws a fluffy cloud.",
    "It runs in green field.",
    "I wave my small hand.",
    "You read a clear sign."
  ];

  static const List<String> kumon5aSentences = [
    "The cat sat on a mat.",
    "A big rat hid in a box.",
    "The fat hen ran to Ben.",
    "Tim has a red hat.",
    "Pam can hop on a log.",
    "The dog dug in the mud.",
    "Tom bit a hot bun.",
    "Kim can fit in the cot.",
    "The bug is on the rug.",
    "A man had a big cap.",
    "Dad had a big red cup.",
    "Sam can fix the net.",
    "The pet is in the van.",
    "Ben met a fat pig.",
    "The pot is on the pan.",
    "Tim cut the big nut.",
    "The bell is on the bed.",
    "Ken dug in the wet pit.",
    "The duck can sit in the tub.",
    "The fox is in the den.",
    "A bat and a cat sat.",
    "Jim had a hot lid.",
    "A hen and a pen fell.",
    "Mom can mop the red rug.",
    "The sun is up on the hill.",
    "The kid hid in the big hut.",
    "The man can tap on a drum.",
    "A bug sat on the cup.",
    "The jam is in the tin.",
    "A pig can sit in mud.",
    "A red fan is on the bed.",
    "The lid is on the hot pan.",
    "The big bug can hop up.",
    "Dan had a sip of pop.",
    "A hen can peck on the bin.",
    "Pat can hum a big song.",
    "A sad pup hid in a den.",
    "The bat hit a big tin.",
    "A fat hen had ten eggs.",
    "The man can run in the sun.",
    "The frog sat on a lily pad.",
    "A bird flew over the tall fence.",
    "The dog slept on the soft rug.",
    "A boy ran with a big kite.",
    "The cow stood in the green field.",
    "A fish swam in the deep pond.",
    "The girl sat by the warm fire.",
    "A bee buzzed around the sweet flower.",
    "The boy climbed up the tall ladder.",
    "A dog barked at the full moon.",
    "The cat slept in the cozy basket.",
    "A bird nested in the high tree.",
    "The man painted on the white wall.",
    "A goat grazed in the green meadow.",
    "The kid played with a round ball.",
    "The snake slid under the big rock.",
    "A girl jumped over a small stream.",
    "The horse stood by the old barn.",
    "A bee landed on the bright petal.",
    "The boy kicked a ball in the park.",
    "The cat chased a mouse under the table.",
    "A bird sang on the thin branch.",
    "The dog ran through the tall grass.",
    "A girl drew a star on the board.",
    "The cow ate grass by the wide river.",
    "The frog leaped into the cool pond.",
    "A boy sailed a boat on the lake.",
    "The man fixed a chair in the room.",
    "The duck swam in the calm water.",
    "A kid hid behind the tall tree."
  ];

  static const List<String> kumon4aSentences = [
    "The frog jumped into the cold pond.",
    "She slid down the smooth hill fast.",
    "The black cat sat on the mat.",
    "The wind blew the tall trees down.",
    "Ben and Tim ran to the shop.",
    "The truck drove down the long road.",
    "The grass grew quickly in the sun.",
    "The flag flapped in the strong wind.",
    "The drum made a loud sound.",
    "The bird flew through the tall trees.",
    "The brown dog ran after the ball.",
    "The frog croaked by the quiet pond.",
    "The fish swam quickly in the tank.",
    "Jack and Tim skipped down the path.",
    "The class sang a happy song.",
    "The black bat flew out of the cave.",
    "The sharp thorns poked through the fence.",
    "The blue flag waved in the wind.",
    "She jumped over the high gate.",
    "The red truck honked as it passed.",
    "The man climbed the tall ladder.",
    "The dog wagged its tail in joy.",
    "The birds chirped loudly in the trees.",
    "The brown bear walked slowly through the forest.",
    "The clock ticked loudly in the room.",
    "The kids clapped their hands after the play.",
    "Tim drew a picture of a boat.",
    "The green frog hopped from stone to stone.",
    "The sun set behind the tall mountain.",
    "The red fish swam in the blue water.",
    "The mouse ran into its little hole.",
    "The cat chased the mouse around the house.",
    "They went to the park and played together.",
    "The monkey swung from tree to tree.",
    "The loud thunder shook the house.",
    "The little bird built a nest on the tree.",
    "The kite soared above the green field.",
    "The boy fished in the calm river.",
    "The dog dug under the tall fence.",
    "The girl painted a bright red flower.",
    "The wind whistled through the narrow valley.",
    "The horse galloped across the wide plain.",
    "The children laughed during the fun game.",
    "The owl perched on the high branch.",
    "The boat sailed across the deep lake.",
    "The rabbit hopped through the soft grass.",
    "The sun shone through the thin clouds.",
    "The kids ran down the steep hill.",
    "The bell rang in the old tower.",
    "The fox sneaked into the dark barn.",
    "The girl danced under the bright stars.",
    "The boy climbed onto the high rock.",
    "The birds fluttered around the blooming garden.",
    "The cat leaped onto the tall shelf.",
    "The wind carried leaves over the wide meadow.",
    "The children sang loudly during the school play.",
    "The dog chased a squirrel through the park.",
    "The frog splashed into the muddy pond.",
    "The girl drew a picture of a tall house.",
    "The sun rose slowly over the calm valley.",
    "The boy sailed a kite above the wide beach.",
    "The horse trotted along the dusty trail.",
    "The kids built a fort with strong sticks.",
    "The owl hooted softly in the dark forest.",
    "The fish darted through the clear stream.",
    "The girl picked berries from the thorny bush."
  ];

  static const List<String> kumon3aSentences = [
    "The bird flew high above the green trees.",
    "I can see the rainbow in the blue sky.",
    "We went for a ride in the warm sun.",
    "She has a red kite with a long tail.",
    "The rain stopped and the sun came out.",
    "Tom sat on the rug to read a book.",
    "A big bear roared in the dark cave.",
    "The tiger ran fast through the tall grass.",
    "The moon shone brightly over the quiet lake.",
    "I saw a fish swim across the clear pond.",
    "We ate lunch under the big green tree.",
    "The snow melted when the warm sun came.",
    "The kite flew high over the tall trees.",
    "She sang a song with a loud voice.",
    "The frog hopped quickly into the cool water.",
    "He ran to catch the yellow bus early.",
    "The bright stars lit up the dark sky.",
    "The book was so good it made me smile.",
    "The big dog sat by the red door.",
    "The butterfly flew by the blooming flower.",
    "She wore a red dress to the party.",
    "I drew a picture of a big house.",
    "We watched the blue car drive down the road.",
    "The bear found honey in the big tree.",
    "I love to play in the warm sand.",
    "The fish swam fast in the cold water.",
    "She played the piano with both hands.",
    "The rain washed the green leaves clean.",
    "We went for a long walk in the park.",
    "The orange cat sat under the green tree.",
    "He wore a shiny red cap on his head.",
    "The boat floated across the calm river.",
    "The kids sang songs by the campfire.",
    "The owl hooted in the quiet night.",
    "The clouds covered the sun for a while.",
    "The brown dog chased its tail happily.",
    "We ran up the hill to see the view.",
    "The horse trotted along the dusty trail.",
    "The girl picked flowers in the bright meadow.",
    "The moon glowed softly behind the thin clouds.",
    "The boy sailed a boat on the calm lake.",
    "The wind carried leaves across the wide field.",
    "The kids built a fort in the shady forest.",
    "The rabbit nibbled carrots in the small garden.",
    "The teacher read a story to the happy class.",
    "The dog followed the boy down the long path.",
    "The stars sparkled above the quiet village.",
    "The girl drew a rainbow with bright colors.",
    "The frog leaped over the small green lily pads.",
    "The sun warmed the sand on the wide beach.",
    "The boy climbed high up the steep mountain.",
    "The birds sang sweetly in the early morning.",
    "The cat slept quietly on the soft cushion.",
    "The boy flew a kite above the green valley.",
    "The wind rustled leaves in the tall oak tree.",
    "The girl danced gracefully under the bright stars.",
    "The dog barked loudly at the passing stranger.",
    "The teacher showed a map to the curious class.",
    "The butterfly landed gently on the colorful flower.",
    "The boy fished quietly by the calm riverbank.",
    "The kids played happily in the warm sunlight.",
    "The horse galloped freely across the open field.",
    "The owl watched silently from the high branch.",
    "The girl painted a picture of a sunny hill."
  ];

  static const List<String> kumon2aSentences = [
    "The dog ran fast to catch the red ball.",
    "We went to the park and played with friends.",
    "Tom likes to ride his bike after school.",
    "She put the red apple on the table again.",
    "The bird flew across the sky with its wings.",
    "I saw a big fish swimming in the pond.",
    "The bus took us to the zoo in the morning.",
    "The snow fell quietly on the ground all night.",
    "We made a big sandcastle on the beach today.",
    "The cat sat on the warm rug all afternoon.",
    "We sang a song together in the music class.",
    "The teacher told us to be quiet in class.",
    "They played a game of tag in the yard.",
    "The big truck passed by with loud noise.",
    "I helped my mom bake cookies in the kitchen.",
    "The children ran to the playground after lunch.",
    "The squirrel climbed the tree to get some nuts.",
    "She painted a picture of a beautiful flower.",
    "The flowers bloomed brightly in the warm sun.",
    "The moon shone brightly in the dark sky.",
    "We ate pizza for dinner at our house.",
    "I rode my bike to the park with my friend.",
    "The dog barked loudly at the passing car.",
    "I wore my red shoes to school today.",
    "The ice cream melted in the hot sun.",
    "We went swimming in the cool blue pool.",
    "The sun is shining bright in the sky.",
    "I ran to catch the bus before it left.",
    "We watched the birds fly high in the sky.",
    "The children played hide and seek in the yard.",
    "She helped me put the books on the shelf.",
    "The car drove slowly down the quiet road.",
    "We saw a rainbow after the rain stopped.",
    "The teacher gave us homework to do tonight.",
    "We made paper boats and sailed them in the water.",
    "The dog slept peacefully in its cozy bed.",
    "We ate lunch outside in the cool breeze.",
    "The stars twinkled brightly in the dark sky.",
    "We built a snowman in the front yard.",
    "The boy flew a kite high above the green hill.",
    "The girl danced happily under the bright moonlight.",
    "We picked ripe apples from the tall orchard trees.",
    "The dog chased a squirrel around the big park.",
    "The children drew pictures during the art class today.",
    "The wind blew gently through the open green valley.",
    "I read a long book under the shady oak tree.",
    "The teacher showed us a map in the geography lesson.",
    "The cat jumped onto the table to eat some food.",
    "We watched a movie at the theater last night.",
    "The boy kicked a ball across the wide field.",
    "The birds built nests high up in the tall trees.",
    "She wrote a letter to her friend after dinner.",
    "The sun set slowly behind the calm blue ocean.",
    "We played a fun game in the backyard yesterday.",
    "The girl planted flowers in the sunny garden today.",
    "The boy climbed a tree to pick ripe cherries.",
    "We watched the sunset from the high hilltop yesterday.",
    "The dog dug a hole in the backyard this morning.",
    "The children sang songs around the warm campfire tonight.",
    "The wind carried the kite high above the wide field.",
    "She drew a picture of a house with colorful crayons.",
    "The boy ran quickly to catch the school bus early.",
    "We built a tall tower with blocks in the classroom.",
    "The cat slept quietly on the windowsill all day.",
    "The teacher read a funny story to the class today.",
    "The kids played soccer on the green field after school.",
    "The moon lit up the path through the dark forest.",
    "The girl helped her mom bake bread in the kitchen."
  ];
}