class EnglishSentences {
  static const List<String> kumon2aSentences = [
    "The cat is on the mat.",
    "I see a big dog.",
    "She has a red hat.",
    "The sun is in the sky.",
    "He likes to run.",
    "The fish is in the pond.",
    "I can jump high.",
    "We go to the park.",
    "The boy is happy.",
    "The bird is in the tree.",
    "The ball is under the bed.",
    "I have a blue pen.",
    "She likes to sing.",
    "The dog is very small.",
    "He has a yellow kite.",
    "We see a big bus.",
    "The apple is red.",
    "I like to play.",
    "The cat is sleeping.",
    "She is eating a cake.",
    "The car is fast.",
    "The rabbit jumps high.",
    "The book is on the table.",
    "He is kicking a ball.",
    "The girl has a doll.",
    "I can see a bird.",
    "The flowers are pink.",
    "The dog runs in the park.",
    "She has a new bag.",
    "The baby is crying.",
    "The boy is riding a bike.",
    "We eat rice and fish.",
    "I like my teddy bear.",
    "The clock is on the wall.",
    "She plays with her sister.",
    "The kite is flying high.",
    "He drinks milk every day.",
    "The cake is very sweet.",
    "We go to school.",
    "The frog jumps into the water."
  ];

  static const List<String> a1Sentences = [
    "My name is Sam.",
    "I live in a small house.",
    "She has a black cat.",
    "We go to school every day.",
    "He is reading a book now.",
    "The weather is very nice today.",
    "I like to eat pizza.",
    "She is my best friend.",
    "The dog is playing in the garden.",
    "He can ride a bicycle.",
    "They are watching TV.",
    "My father works in a hospital.",
    "We have lunch at 12 o’clock.",
    "She likes to draw pictures.",
    "The bus arrives at 8 a.m.",
    "I want to buy a new phone.",
    "He is learning English.",
    "The children are very happy.",
    "I go to bed at 10 p.m.",
    "She is wearing a red dress.",
    "He plays football with his friends.",
    "I have two brothers and one sister.",
    "My mother makes delicious cakes.",
    "They are listening to music.",
    "We go shopping on Sundays.",
    "I don’t like cold weather.",
    "The baby is sleeping in the crib.",
    "He has a big car.",
    "She works in a bank.",
    "The sun is shining brightly.",
    "I can speak a little German.",
    "My favorite color is blue.",
    "We visit our grandparents on weekends.",
    "He is writing a letter to his friend.",
    "I like to swim in the summer.",
    "She goes to the gym twice a week.",
    "The coffee is too hot.",
    "He is wearing a blue jacket.",
    "I want to travel to Japan.",
    "She always wakes up early."
  ];
}
